### ISSUE TITLE
issue with inputs

### ISSUE THREAD

**Issue by gayanscorpio** [nadavspi/react-bookshelf#1]
Hi,

my route is : http://localhost:3000/admin/bookshelf/add

but when i was trying to add a new book , the bellow error occurred,

Error: Failed to save.

so, please be kind enough to go through this one, and any thing wrong from my side?

so, how to save data, when we submit(save) , is it on Database?

**Comment by nadavspi** [comment]
Hi! This thing uses `json-server` as a fake API. Make sure it's running using `npm run api`: that should help. Note that this is just an incomplete experiment, but I think save should work.

**Comment by gayanscorpio** [comment]
Hi nadavspi ,

thank u very much, for update.

**Comment by nadavspi** [comment]
Thanks for checking it out! I should do some more work on it.
